services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=demo-spring-boot'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
